name: Auto Sync to GitHub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Se ejecuta cada 6 horas

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git push